### ISSUE TITLE
g++: error: unrecognized command-line option '-mthreads'; did you mean '-pthread'?

### ISSUE THREAD

**Issue by gasgallo** [x1unix/docker-go-mingw#20]
As of title, I get this error when using the default command:
```
docker run --rm -it -v /YourPackageSrc:/go/work \
    -w /go/work \
    x1unix/go-mingw go build .
```
Any idea what could be the cause of this?

**Comment by WindLi001** [comment]
I think that's because only CC=x86_64-w64-mingw32-cc is set, but CXX is NOT set in the docker image. So the pure C files in CGO can be cross compiled, but the C++ files cannot.
To resolve this issue, the steps below are needed when build the docker image.
1. sudo apt install g++-mingw-w64-x86-64
2. Adding **CXX=x86_64-w64-mingw32-g++** in the environment variables.

**Comment by x1unix** [comment]
@WindLi001 @gasgallo fixed
